apiVersion: v1
kind: Service
metadata:
  name: monero
  labels:
    app: monero
spec:
  selector:
    app: monero
  ports:
    - name: p2p
      port: 18080
    - name: restricted-rpc
      port: 18089

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: monero
spec:
  serviceName: "monero"

  selector:
    matchLabels:
      app: monero

  template:
    metadata:
      labels:
        app: monero
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: monero
          image: index.docker.io/utxobr/monerod@sha256:19ba5793c00375e7115469de9c14fcad928df5867c76ab5de099e83f646e175d
          command:
            - monerod
            - --non-interactive
            - --enable-dns-blocklist
            - --no-igd
            - --prune-blockchain
            - --public-node
            - --rpc-restricted-bind-ip=0.0.0.0
            - --rpc-restricted-bind-port=18089
            - --p2p-bind-ip=0.0.0.0
            - --p2p-bind-port=18080
            - --data-dir=/data
            - --testnet
          readinessProbe:
            periodSeconds: 15
            initialDelaySeconds: 15
            failureThreshold: 5
            httpGet:
              path: /get_info
              port: restricted-rpc
          ports:
            - containerPort: 18089
              name: restricted-rpc
            - containerPort: 18080
              name: p2p
          volumeMounts:
            - name: data
              mountPath: /data

  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          kapp.k14s.io/owned-for-deletion: ""
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
