kind: MoneroNetwork
apiVersion: utxo.com.br/v1alpha1
metadata:
  name: network
spec:
  replicas: 3
  template:
    spec:
      monerod:
        args:
          - --regtest
          - --fixed-difficulty=1
