{
 "title": "monerod",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "peers",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    { "expr": "monero_peers_new", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "connections",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "valueName": "total",
   "targets": [
    { "expr": "monero_connections", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "rpc calls /m",
   "type": "graph",
   "description": "number of nodes banned",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(monero_rpc_count[1m])", "legendFormat": "{{ method }}" }
   ]
  },
  {
   "title": "rpc time spent in last min",
   "type": "graph",
   "description": "number of nodes banned",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "increase(monero_rpc_time[1m])", "legendFormat": "{{ method }}" }
   ]
  },
  {
   "title": "connections live time distribution",
   "type": "graph",
   "description": "number of nodes banned",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "monero_connections_livetime", "legendFormat": "{{ quantile }}" }
   ]
  },
  {
   "title": "last block txn fee distribution",
   "type": "graph",
   "description": "number of nodes banned",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "monero_last_block_txn_fee / 1000000000000",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "mempool size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "monero_mempool_bytes_total", "legendFormat": "total" }
   ]
  },
  {
   "title": "network traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "rate(monero_net_total_in_bytes[1m])"
    },
    {
     "expr": "rate(monero_net_total_out_bytes[1m])"
    }
   ]
  },
  {
   "title": "last block txn vout distribution",
   "type": "graph",
   "description": "number of nodes banned",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "monero_last_block_vin", "legendFormat": "{{ quantile }}" }
   ]
  },
  {
   "title": "last block txn vout distribution",
   "type": "graph",
   "description": "number of nodes banned",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "monero_last_block_vout", "legendFormat": "{{ quantile }}" }
   ]
  },
  {
   "title": "last block txn size distribution",
   "type": "graph",
   "description": "number of nodes banned",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "monero_last_block_txn_size", "legendFormat": "{{ quantile }}" }
   ]
  },
  {
   "title": "mempoool fee /B total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "monero_mempool_fee_total / 1000000000000",
     "legendFormat": "fee total"
    }
   ]
  },
  {
   "title": "txs in the pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "monero_mempool_txs_total", "legendFormat": "count" }
   ]
  },
  { "title": "overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "monerod uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - monero_info_start_time",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "statuses",
   "type": "stat",
   "description": "`0` - no\n`1` - yes",
   "gridPos": { "h": 2, "w": 8, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monero_info_busy_syncing", "legendFormat": "syncing" },
    { "expr": "monero_info_offline", "legendFormat": "offline" },
    { "expr": "monero_info_mainnet", "legendFormat": "mainnet" }
   ]
  },
  {
   "title": "last block versions",
   "type": "stat",
   "description": "The amount of new atomic units generated in this block and rewarded to the miner.",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monero_last_block_header_major_version",
     "legendFormat": "major"
    },
    {
     "expr": "monero_last_block_header_minor_version",
     "legendFormat": "minor"
    }
   ]
  },
  {
   "title": "last block elapsed time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - monero_last_block_header_timestamp"
    }
   ]
  },
  {
   "title": "rpc conns count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "monero_info_rpc_connections_count",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "transactions",
   "type": "graph",
   "description": "`tx_count` - unsigned int; Total number of non-coinbase transaction in the chain.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "monero_info_tx_count", "legendFormat": "total" },
    {
     "expr": "monero_last_block_header_num_txes",
     "legendFormat": "last block"
    }
   ]
  },
  {
   "title": "alternative blocks",
   "type": "graph",
   "description": "`alt_blocks_count` - unsigned int; Number of alternative blocks to main chain.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "monero_info_alt_blocks_count", "legendFormat": "count" }
   ]
  },
  {
   "title": "block size",
   "type": "graph",
   "description": "`block_size_median` - unsigned int; Median block size of latest 100 blocks\n\n`block_size_limit` - unsigned int; Maximum allowed block size",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "monero_info_block_size_limit", "legendFormat": "limit" },
    { "expr": "monero_info_block_size_median", "legendFormat": "median" },
    {
     "expr": "monero_last_block_header_block_size",
     "legendFormat": "last block size"
    }
   ]
  },
  {
   "title": "difficulty",
   "type": "graph",
   "description": "difficulty\n`block_size_limit` - unsigned int; Maximum allowed block size",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    { "expr": "monero_info_difficulty", "legendFormat": "difficulty" }
   ]
  },
  {
   "title": "peerlist",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "monero_info_grey_peerlist_size", "legendFormat": "grey" },
    {
     "expr": "monero_info_white_peerlist_size",
     "legendFormat": "white"
    }
   ]
  },
  {
   "title": "height",
   "type": "graph",
   "description": "- `incoming_connections_count`:  number of peers connected to and pulling from your node.\n- `outgoing_connections_count `:  Number of peers that you are connected to and getting information from",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "monero_info_height", "legendFormat": "height" }
   ]
  },
  {
   "title": "last block rewards",
   "type": "graph",
   "description": "The amount of new atomic units generated in this block and rewarded to the miner.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "monero_last_block_header_reward / 1000000000000",
     "legendFormat": "rewards"
    }
   ]
  },
  {
   "title": "connections",
   "type": "graph",
   "description": "- `incoming_connections_count`:  number of peers connected to and pulling from your node.\n- `outgoing_connections_count `:  Number of peers that you are connected to and getting information from",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "monero_info_outgoing_connections_count",
     "legendFormat": "outgoing"
    },
    {
     "expr": "monero_info_incoming_connections_count",
     "legendFormat": "incoming"
    }
   ]
  },
  {
   "title": "bans",
   "type": "graph",
   "description": "number of nodes banned",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "monero_bans", "legendFormat": "bans" }
   ]
  },
  {
   "title": "base fee estimate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "monero_fee_estimate", "legendFormat": "estimate" }
   ]
  },
  {
   "title": "peers height divergence",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "monero_height_divergence", "legendFormat": "{{ quantile }}" }
   ]
  },
  {
   "title": "weird cases",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "monero_mempool_num_failing", "legendFormat": "failing" },
    {
     "expr": "monero_mempool_num_double_spends",
     "legendFormat": "double spends"
    },
    { "expr": "monero_mempool_num_not_relayed", "legendFormat": "no relayed" },
    { "expr": "monero_mempool_num_10m", "legendFormat": "10m" }
   ]
  },
  { "title": "mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "oldest tx in mempool",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monero_mempool_oldest * 1000", "legendFormat": "timestamp" }
   ]
  }
 ]
}