// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoneroMiningNodeSet) DeepCopyInto(out *MoneroMiningNodeSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoneroMiningNodeSet.
func (in *MoneroMiningNodeSet) DeepCopy() *MoneroMiningNodeSet {
	if in == nil {
		return nil
	}
	out := new(MoneroMiningNodeSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MoneroMiningNodeSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoneroMiningNodeSetList) DeepCopyInto(out *MoneroMiningNodeSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MoneroMiningNodeSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoneroMiningNodeSetList.
func (in *MoneroMiningNodeSetList) DeepCopy() *MoneroMiningNodeSetList {
	if in == nil {
		return nil
	}
	out := new(MoneroMiningNodeSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MoneroMiningNodeSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoneroMiningNodeSetSpec) DeepCopyInto(out *MoneroMiningNodeSetSpec) {
	*out = *in
	in.Xmrig.DeepCopyInto(&out.Xmrig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoneroMiningNodeSetSpec.
func (in *MoneroMiningNodeSetSpec) DeepCopy() *MoneroMiningNodeSetSpec {
	if in == nil {
		return nil
	}
	out := new(MoneroMiningNodeSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoneroMiningNodeSetStatus) DeepCopyInto(out *MoneroMiningNodeSetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoneroMiningNodeSetStatus.
func (in *MoneroMiningNodeSetStatus) DeepCopy() *MoneroMiningNodeSetStatus {
	if in == nil {
		return nil
	}
	out := new(MoneroMiningNodeSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoneroNetwork) DeepCopyInto(out *MoneroNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoneroNetwork.
func (in *MoneroNetwork) DeepCopy() *MoneroNetwork {
	if in == nil {
		return nil
	}
	out := new(MoneroNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MoneroNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoneroNetworkList) DeepCopyInto(out *MoneroNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MoneroNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoneroNetworkList.
func (in *MoneroNetworkList) DeepCopy() *MoneroNetworkList {
	if in == nil {
		return nil
	}
	out := new(MoneroNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MoneroNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoneroNetworkSpec) DeepCopyInto(out *MoneroNetworkSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoneroNetworkSpec.
func (in *MoneroNetworkSpec) DeepCopy() *MoneroNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(MoneroNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoneroNetworkStatus) DeepCopyInto(out *MoneroNetworkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoneroNetworkStatus.
func (in *MoneroNetworkStatus) DeepCopy() *MoneroNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(MoneroNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoneroNetworkTemplate) DeepCopyInto(out *MoneroNetworkTemplate) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoneroNetworkTemplate.
func (in *MoneroNetworkTemplate) DeepCopy() *MoneroNetworkTemplate {
	if in == nil {
		return nil
	}
	out := new(MoneroNetworkTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoneroNodeSet) DeepCopyInto(out *MoneroNodeSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoneroNodeSet.
func (in *MoneroNodeSet) DeepCopy() *MoneroNodeSet {
	if in == nil {
		return nil
	}
	out := new(MoneroNodeSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MoneroNodeSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoneroNodeSetList) DeepCopyInto(out *MoneroNodeSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MoneroNodeSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoneroNodeSetList.
func (in *MoneroNodeSetList) DeepCopy() *MoneroNodeSetList {
	if in == nil {
		return nil
	}
	out := new(MoneroNodeSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MoneroNodeSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoneroNodeSetSpec) DeepCopyInto(out *MoneroNodeSetSpec) {
	*out = *in
	out.Tor = in.Tor
	in.Monerod.DeepCopyInto(&out.Monerod)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoneroNodeSetSpec.
func (in *MoneroNodeSetSpec) DeepCopy() *MoneroNodeSetSpec {
	if in == nil {
		return nil
	}
	out := new(MoneroNodeSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoneroNodeSetStatus) DeepCopyInto(out *MoneroNodeSetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Tor = in.Tor
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoneroNodeSetStatus.
func (in *MoneroNodeSetStatus) DeepCopy() *MoneroNodeSetStatus {
	if in == nil {
		return nil
	}
	out := new(MoneroNodeSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoneroNodeStatusTor) DeepCopyInto(out *MoneroNodeStatusTor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoneroNodeStatusTor.
func (in *MoneroNodeStatusTor) DeepCopy() *MoneroNodeStatusTor {
	if in == nil {
		return nil
	}
	out := new(MoneroNodeStatusTor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoneroTorConfig) DeepCopyInto(out *MoneroTorConfig) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoneroTorConfig.
func (in *MoneroTorConfig) DeepCopy() *MoneroTorConfig {
	if in == nil {
		return nil
	}
	out := new(MoneroTorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonerodConfig) DeepCopyInto(out *MonerodConfig) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonerodConfig.
func (in *MonerodConfig) DeepCopy() *MonerodConfig {
	if in == nil {
		return nil
	}
	out := new(MonerodConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XmrigConfig) DeepCopyInto(out *XmrigConfig) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XmrigConfig.
func (in *XmrigConfig) DeepCopy() *XmrigConfig {
	if in == nil {
		return nil
	}
	out := new(XmrigConfig)
	in.DeepCopyInto(out)
	return out
}
